# Generated by Django 5.1.4 on 2026-01-13 16:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Main blog content (supports HTML)'),
        ),
    ]
