# Generated by Django 5.1.4 on 2026-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='og_title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Full absolute URL if different from path', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter share image', null=True, upload_to='blog/twitter/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter title', max_length=200),
        ),
    ]
