# Generated by Django 5.1.4 on 2026-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_og_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=200),
        ),
    ]
