# Generated by Django 5.1.4 on 2026-01-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('width_mm', models.IntegerField(help_text='Width in mm')),
                ('height_mm', models.IntegerField(help_text='Height in mm')),
                ('bg_color', models.CharField(default='white', help_text='e.g. white, lightblue', max_length=20)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('content_body', models.TextField(help_text='SEO content body')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/%Y/%m/%d/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_tool.countryrule')),
            ],
        ),
    ]
