# Generated by Django 5.1.4 on 2026-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrule',
            name='flag_emoji',
            field=models.CharField(blank=True, default='🏳️', help_text='Country flag emoji', max_length=10),
        ),
    ]
