# Generated by Django 5.1.4 on 2026-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0003_countryrule_flag_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrule',
            name='default_target_kb',
            field=models.IntegerField(default=350, help_text='Pre-set KB target for specific tools'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='faq_json',
            field=models.TextField(blank=True, help_text="JSON format for FAQ: [{'q': '...', 'a': '...'}]"),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='guide_steps',
            field=models.TextField(blank=True, help_text='How-to guide steps (Markdown/HTML supported)'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='h1',
            field=models.CharField(blank=True, help_text='Main heading for the page', max_length=200),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Intro paragraph after H1'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='Whether this is an exam-specific tool'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='is_tool',
            field=models.BooleanField(default=False, help_text='Whether this is a utility-specific tool (e.g., compressor)'),
        ),
    ]
