# Generated by Django 5.1.4 on 2026-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0004_countryrule_default_target_kb_countryrule_faq_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrule',
            name='exam_country',
            field=models.CharField(blank=True, help_text='e.g. India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='exam_organization',
            field=models.CharField(blank=True, help_text='e.g. TNPSC', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='exam_state',
            field=models.CharField(blank=True, help_text='e.g. Tamil Nadu', max_length=100, null=True),
        ),
    ]
