# Generated by Django 5.1.4 on 2026-01-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0005_countryrule_exam_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryrule',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
