# Generated by Django 5.1.4 on 2026-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0006_alter_countryrule_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrule',
            name='height_px',
            field=models.IntegerField(blank=True, help_text='Exact height in pixels (overrides mm)', null=True),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='requires_name_overlay',
            field=models.BooleanField(default=False, help_text='Requires Name/Date tag on photo'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='width_px',
            field=models.IntegerField(blank=True, help_text='Exact width in pixels (overrides mm)', null=True),
        ),
    ]
