# Generated by Django 5.1.4 on 2026-01-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0007_countryrule_height_px_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SnapFixer', max_length=200)),
                ('logo', models.ImageField(help_text='Upload your site logo', upload_to='settings/')),
                ('favicon', models.ImageField(help_text='Upload your favicon (ico/png)', upload_to='settings/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
