# Generated by Django 5.1.4 on 2026-01-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The URL path (e.g., /, /about/, /contact/)', max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='meta/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='meta/')),
                ('canonical_url', models.CharField(blank=True, help_text='Full absolute URL if different from path', max_length=255)),
            ],
            options={
                'verbose_name': 'Page Meta Tag',
                'verbose_name_plural': 'Page Meta Tags Manager',
            },
        ),
    ]
