# Generated by Django 5.1.4 on 2026-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0009_pagemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrule',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Full absolute URL if different from path', max_length=255),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social media share image', null=True, upload_to='tool/og/'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=200),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter description'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter share image', null=True, upload_to='tool/twitter/'),
        ),
        migrations.AddField(
            model_name='countryrule',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter title', max_length=200),
        ),
    ]
