# Generated by Django 5.1.4 on 2026-01-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_tool', '0010_countryrule_canonical_url_countryrule_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedphoto',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
